version: '3'  
services:  
  db:  
    image: mariadb  
    env_file:  
      - .env
    volumes:  
      - db_data:/var/lib/mysql  
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql  

  node-service:  
    build: ./api  
    env_file:  
      - .env
    depends_on: 
      - db

  nginx:
    build: ./nginx  
    ports:  
      - "8080:80"
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:  
      - node-service

volumes:  
  db_data:  
  